title: Recollate jekyll+webpack test
email: github@recollate.com
description: ""
url: ""
twitter_username: recollateagency
github_username:  recollate
permalink: "/"

markdown: kramdown

destination: docs

